mode = "dark"

accent = "#b8c3ff"
selection = "#2e2e3a"
muted = "#90909a"
border = "#2e2e36"

background = "#121318"
dark_background = "#121318"
darker_background = "#0a0a0e"
lighter_background = "#232329"

foreground = "#e3e1e9"
dark_foreground = "#c6c5d0"
light_foreground = "#e3e1e9"
bright_foreground = "#ffffff"

red = "#ffb4ab"
yellow = "#e4bad9"
orange = "#e4bad9"
green = "#c3c5dd"
cyan = "#56b6c2"
blue = "#b8c3ff"
magenta = "#bb9af7"
brown = "#6b5b55"

bright_red = "#ffb4ab"
bright_yellow = "#e4bad9"
bright_green = "#c3c5dd"
bright_cyan = "#56b6c2"
bright_blue = "#b8c3ff"
bright_magenta = "#bb9af7"
