[colors.primary]
background = "#121318"
foreground = "#e3e1e9"
[colors.normal]
black = "#121318"
red = "#ffb4ab"
green = "#c3c5dd"
yellow = "#e4bad9"
blue = "#b8c3ff"
magenta = "#bb9af7"
cyan = "#56b6c2"
white = "#e3e1e9"
[colors.bright]
black = "#90909a"
red = "#ffb4ab"
green = "#c3c5dd"
yellow = "#e4bad9"
blue = "#b8c3ff"
magenta = "#bb9af7"
cyan = "#56b6c2"
white = "#ffffff"
