{
  "$schema": "https://opencode.ai/theme.json",
  "defs": {
    "bg": "{{background}}",
    "bgDark": "{{darker_background}}",
    "bgPanel": "{{lighter_background}}",
    "bgElement": "{{selection}}",
    "border": "{{border}}",
    "borderSubtle": "{{border}}",
    "fg": "{{foreground}}",
    "fgBright": "{{bright_foreground}}",
    "fgMuted": "{{muted}}",
    "fgSubtle": "{{dark_foreground}}",
    "accent": "{{accent}}",
    "red": "{{red}}",
    "green": "{{green}}",
    "yellow": "{{yellow}}",
    "orange": "{{orange}}",
    "cyan": "{{cyan}}",
    "blue": "{{blue}}",
    "magenta": "{{magenta}}",
    "selection": "{{selection}}"
  },
  "theme": {
    "primary": { "dark": "accent", "light": "accent" },
    "secondary": { "dark": "fgMuted", "light": "fgMuted" },
    "accent": { "dark": "accent", "light": "accent" },
    "error": { "dark": "red", "light": "red" },
    "warning": { "dark": "yellow", "light": "yellow" },
    "success": { "dark": "green", "light": "green" },
    "info": { "dark": "blue", "light": "blue" },
    "text": { "dark": "fg", "light": "fg" },
    "textMuted": { "dark": "fgMuted", "light": "fgMuted" },
    "background": { "dark": "bg", "light": "bg" },
    "backgroundPanel": { "dark": "bgPanel", "light": "bgPanel" },
    "backgroundElement": { "dark": "bgElement", "light": "bgElement" },
    "border": { "dark": "border", "light": "border" },
    "borderActive": { "dark": "accent", "light": "accent" },
    "borderSubtle": { "dark": "borderSubtle", "light": "borderSubtle" },
    "diffAdded": { "dark": "green", "light": "green" },
    "diffRemoved": { "dark": "red", "light": "red" },
    "diffContext": { "dark": "fgMuted", "light": "fgMuted" },
    "diffHunkHeader": { "dark": "fgSubtle", "light": "fgSubtle" },
    "diffHighlightAdded": { "dark": "green", "light": "green" },
    "diffHighlightRemoved": { "dark": "red", "light": "red" },
    "diffAddedBg": { "dark": "bgPanel", "light": "bgPanel" },
    "diffRemovedBg": { "dark": "bgPanel", "light": "bgPanel" },
    "diffContextBg": { "dark": "bg", "light": "bg" },
    "diffLineNumber": { "dark": "fgMuted", "light": "fgMuted" },
    "diffAddedLineNumber": { "dark": "green", "light": "green" },
    "diffRemovedLineNumber": { "dark": "red", "light": "red" },
    "diffAddedLineNumberBg": { "dark": "bgElement", "light": "bgElement" },
    "diffRemovedLineNumberBg": { "dark": "bgElement", "light": "bgElement" },
    "markdownText": { "dark": "fg", "light": "fg" },
    "markdownHeading": { "dark": "accent", "light": "accent" },
    "markdownLink": { "dark": "blue", "light": "blue" },
    "markdownLinkText": { "dark": "cyan", "light": "cyan" },
    "markdownCode": { "dark": "green", "light": "green" },
    "markdownBlockQuote": { "dark": "fgMuted", "light": "fgMuted" },
    "markdownEmph": { "dark": "yellow", "light": "yellow" },
    "markdownStrong": { "dark": "fgBright", "light": "fgBright" },
    "markdownHorizontalRule": { "dark": "border", "light": "border" },
    "markdownListItem": { "dark": "fg", "light": "fg" },
    "markdownListEnumeration": { "dark": "fgMuted", "light": "fgMuted" },
    "markdownImage": { "dark": "blue", "light": "blue" },
    "markdownImageText": { "dark": "cyan", "light": "cyan" },
    "markdownCodeBlock": { "dark": "fg", "light": "fg" },
    "syntaxComment": { "dark": "fgMuted", "light": "fgMuted" },
    "syntaxKeyword": { "dark": "magenta", "light": "magenta" },
    "syntaxFunction": { "dark": "accent", "light": "accent" },
    "syntaxVariable": { "dark": "cyan", "light": "cyan" },
    "syntaxString": { "dark": "green", "light": "green" },
    "syntaxNumber": { "dark": "yellow", "light": "yellow" },
    "syntaxType": { "dark": "cyan", "light": "cyan" },
    "syntaxOperator": { "dark": "fg", "light": "fg" },
    "syntaxPunctuation": { "dark": "fgSubtle", "light": "fgSubtle" }
  }
}
